version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true

# Options for custom base configuration file
# clash_rule_base = "base/forcerule.yml"
#surge_rule_base = "base/surge.conf"
#surfboard_rule_base = "base/surfboard.conf"
#mellow_rule_base = "base/mellow.conf"
#quan_rule_base = "base/quan.conf"
#quanx_rule_base = "base/quanx.conf"

# Options for adding emojis
#add_emoji = true
#remove_old_emoji = true

# Options for filtering nodes
#include_remarks = []
#exclude_remarks = []

[[custom_groups]]
# import = "snippets/v_groups.toml"
import = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/v_groups.toml"

[[rulesets]]
# import = "snippets/dns_rulesets.toml"
import = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/dns_rulesets.toml"

# [[template_args]]
# key = "clash.dns.port"
# value = "5353"
