[[custom_groups]]
name = "🗽 Proxies"
type = "select"
rule = [
    "[]🇺🇸 VKVM_US",
    "[]🇺🇸 Bandwagon",
    "[]🇺🇸 Cloudcone",
    "[]🇨🇦 Gullo"
]

[[custom_groups]]
name = "📽 YouTube"
type = "select"
rule = [
    "[]🇺🇸 VKVM_US",
    "[]🇺🇸 Bandwagon",
    "[]🇺🇸 Cloudcone",
    "[]🇨🇦 Gullo"
]

[[custom_groups]]
name = "⚡ Google"
type = "select"
rule = [
    "[]🇺🇸 VKVM_US",
    "[]🇺🇸 Bandwagon",
    "[]🇺🇸 Cloudcone",
    "[]🇨🇦 Gullo"
]

[[custom_groups]]
name = "💬 OpenAI"
type = "select"
rule = [
    "[]🇺🇸 VKVM_US",
    "[]🇺🇸 Bandwagon",
    "[]🇺🇸 Cloudcone",
    "[]🇨🇦 Gullo"
]

[[custom_groups]]
name = " & Ⓜ️"
type = "select"
rule = [
    "[]🇺🇸 VKVM_US",
    "[]🇺🇸 Bandwagon",
    "[]🇺🇸 Cloudcone",
    "[]🇨🇦 Gullo"
]

[[custom_groups]]
name = "👑 Emby"
type = "select"
rule = [
    "[]🇺🇸 VKVM_US",
    "[]🇺🇸 Bandwagon",
    "[]🇺🇸 Cloudcone",
    "[]🇨🇦 Gullo",
    "[]DIRECT",
]

[[custom_groups]]
name = "🎮 Switch"
type = "select"
rule = [
    "[]🇺🇸 VKVM_US",
    "[]🇺🇸 Bandwagon",
    "[]🇺🇸 Cloudcone",
    "[]🇨🇦 Gullo",
    "[]DIRECT",
]

[[custom_groups]]
name = "🎮 Game"
type = "select"
rule = [
    "[]🇺🇸 VKVM_US",
    "[]🇺🇸 Bandwagon",
    "[]🇺🇸 Cloudcone",
    "[]🇨🇦 Gullo",
    "[]DIRECT",
]

[[custom_groups]]
name = "🌍 Foreign_media"
type = "select"
rule = [
    "[]🇺🇸 VKVM_US",
    "[]🇺🇸 Bandwagon",
    "[]🇺🇸 Cloudcone",
    "[]🇨🇦 Gullo",
    "[]DIRECT",
]

[[custom_groups]]
name = "🎥 NETFLIX"
type = "select"
rule = [
    "[]🇺🇸 VKVM_US",
    "[]🇺🇸 Bandwagon",
    "[]🇺🇸 Cloudcone",
    "[]🇨🇦 Gullo"
]

[[custom_groups]]
name = "💰 PayPal"
type = "select"
rule = [
    "[]🇺🇸 VKVM_US",
    "[]🇺🇸 Bandwagon",
    "[]🇺🇸 Cloudcone",
    "[]🇨🇦 Gullo"
]

[[custom_groups]]
name = "⏱ Speedtest"
type = "select"
rule = [".*", "[]DIRECT"]
use = ["cc",  "vkvm_us", "bandwagon", "gullo" ]

[[custom_groups]]
name = "🛑 Global_interception"
type = "select"
rule = ["[]REJECT", "[]DIRECT"]

[[custom_groups]]
name = "🎯 Domestic"
type = "select"
rule = ["[]DIRECT"]

[[custom_groups]]
name = "🐟 Slipped"
type = "select"
rule = ["[]🗽 Proxies", "[]DIRECT"]

[[custom_groups]]
name = "🇺🇸 VKVM_US"
type = "select"
use = ["vkvm_us"]
# lazy = true

[[custom_groups]]
name = "🇺🇸 Bandwagon"
type = "select"
use = ["bandwagon"]
# lazy = true

[[custom_groups]]
name = "🇺🇸 Cloudcone"
type = "select"
use = ["cc"]
# lazy = true

[[custom_groups]]
name = "🇨🇦 Gullo"
type = "select"
use = ["gullo"]
# lazy = true
